baseURL = '/'
languageCode = 'zh-cn'
title = 'Jh Wu 作品集'
theme = 'PaperMod'

[params]
env = "production"
author = "Jh Wu"
description = "Java 后端开发"

[params.profileMode]
enabled = true
title = "你好，我是 Jh Wu 👋"
subtitle = "正在寻找 Java 开发实习/校招机会。擅长 SpringCloud、Redis、MySQL 调优。"
# 记得在 static 文件夹放一个 head.png
imageUrl = ""
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "查看我的项目"
url = "/posts"
[[params.profileMode.buttons]]
name = "关于我"
url = "/about"

# 社交链接（主页会显示图标）
[[params.socialIcons]]
name = "github"
url = "https://github.com/JhWuuuy"
[[params.socialIcons]]
name = "email"
url = "mailto:你的邮箱"